### ISSUE TITLE
CURLY_BRACE in Values throw error

### ISSUE THREAD

**Issue by wq9** [devinwl/keyvalues-php#6]
In `dota_pak01/scripts/items/items_game.txt`, there is the following (item 5086: Span of Black Nihility):

```vdf
			"static_attributes"
			{
				"static socket 1"
				{
					"attribute_class"		"socket"
					"value"		"socket { required_hero: 'npc_dota_hero_nightstalker' gem_def_index: 3005 } asset_modifier: 130"
				}
				"international tag"
				{
					"attribute_class"		"international_tag"
					"value"		"2015"
				}
			}
```

The parser will end with `Not properly formed key-value structure` after encountering `{` in the value.

**Comment by devinwl** [comment]
Fixed in c705b2281a09f3b16f1e6eddcb028caef08517ff

I added an additional test to cover this case.  Thanks for the bug report!
