### ISSUE TITLE
Wrong output when key contains '.'

### ISSUE THREAD

**Issue by wq9** [devinwl/keyvalues-php#7]
The following test case produces the wrong output:

https://gist.github.com/wq9/280f3738b0428581534a#file-wrong-json-L48

The keys are wrong and the depth level is also wrong.

**Comment by devinwl** [comment]
Thanks for catching this.  I chose the '.' character to separate the path depths in the VDF files.  If that character was in the path somewhere then the wrong path depth is returned when parsing finishes.

For now I changed it to something unlikely to be encountered in a file, although this is just more of a patch.  I'll have to look into a better parsing method in the future.
